version: "3.7"
services:  
  dev:
    container_name: 20-questions
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - type: bind
        source: ./src
        target: /srv
        consistency: cached
    env_file:
      - .env
    restart: always